### PR TITLE
Added option to return data as raw data

### PR DESCRIPTION
**Pull request by Istenes**
If someone wants to use newer API's to save the image to disk it is better for us to return raw data instead of base64 data. This will save some encoding time and filespace.

### CODE REVIEW

**Comment by chuan-su** [comment]
+1

**Comment by gustavidstrom** [comment]
+1

**Comment by owencm** [comment]
lgtm

**Comment by owencm** [comment]
Actually, Istenes - can you please update the sample to reflect this change?

**Comment by Istenes** [comment]
Sure, I'm actually updating it a bit more, instead of a normal array it would be better to return as a typed array, to use with Websockets, XHR's or simply to make it a Blob to use with FileReaders and FileWriters.

I will update the sample when these features are fixed.

**Pull request merged**
